Fix some parsing logic in meminfo-writer
QubesOS/qubes-linux-utils pull request #86
Opened 2022-06-25 06:23 UTC by DemiMarie

Not a security issue as the input is trusted.

2022-06-27 03:34 UTC, DemiMarie commented
PipelineRetry

2022-07-22 16:35 UTC, DemiMarie commented
PipelineRetryFailed

2022-10-11 19:58 UTC, marmarek commented on qmemman/meminfo-writer.c
> +		switch (*ptr) {
This function is executed at least 10 times per second, in _every_ VM. Can you verify that your change do not make it any slower than it was? For example extract it into a tight loop and measure time for 10000 iterations or such.

2022-12-08 14:20 UTC, marmarek requested changes
(see comment above, just marking PR as requiring something, even if it isn't strictly change request)

2025-06-21 00:39 UTC, closed without merging

2025-06-21 00:39 UTC, marmarek commented
Abandoned for over 2 years.