Path sanitization for qfile-copy
QubesOS/qubes-linux-utils pull request #87
Opened 2022-07-21 20:03 UTC by DemiMarie

This adds path sanitization for qfile-copy and avoids relying on chroot and bind-mounts for security.  This is necessary for several reasons:

- It turns out that the bind-mount solution does not work in the presence of `MS_PRIVATE` mount namespaces.  These are created by Podman and `pam_namespace.so`.  If `pam_namespace.so` is in use, or if `~/QubesIncoming` (or a subdirectory) is bind-mounted into a Podman container, the vulnerability described in Qubes Security Bulletin 015 might be exploitable, at least in theory.  Flatpak and Snap do create new mount spaces but are not affected.
- Right now, symbolic links under `~/QubesIncoming` can point to anywhere.  This means that `echo > ~/QubesIncoming/untrustedqube/x` might overwrite `~/.profile` or something else bad.
- There is currently no restriction on allowed file names.  This means that Trojan Source-style attacks might be possible.

2022-07-26 15:12 UTC, marmarek requested changes

2022-07-26 15:12 UTC, marmarek commented on qrexec-lib/unpack.c
> +    static char *path_dup = NULL;
`static` here is asking for troubles, you don't really need preserving state between invocations (and that would actually be a bug). And freeing `path_dup` only on subsequent call is asking for use-after-free bugs (IOW, it's better to risk memory leak than use-after-free, but of course preferably there should be neither). Please change this.

2022-07-26 15:12 UTC, marmarek commented on qrexec-lib/unpack.c
> +            assert(*next == '/');
I don't think you need this assert, it's a definition of `strchr` (as usual - don't add unit tests of libc in random places).

2022-07-26 15:12 UTC, marmarek commented on qrexec-lib/unpack.c
> +        if (*path_dup) {
I don't think you can reach this with `*path_dup == 0`, so this `if` is pointless. It may be even worth handling empty path early, to make it clear what happens in that case.

2022-07-26 15:12 UTC, marmarek commented on qrexec-lib/unpack.c
> +static int open_safe(int dirfd, const char *path, const char **last_segment)
Since this function actually opens a directory, not the `path` itself, I'd prefer to name it `opendir_safe` or similar.
And also, it could use a comment explaining why it is here at all (specifically, to enforce `O_NOFOLLOW` at each path component, not just the last one).

2022-07-26 15:12 UTC, marmarek commented on qrexec-lib/unpack.c
> +        code_point = *untrusted_c - 0xC0;
For consistency, better to write `*untrusted_c & 0x1F`

2022-07-26 15:12 UTC, marmarek commented on qrexec-lib/unpack.c
> +            code_point = *untrusted_c - 0xE0;
For consistency, better write `*untrusted_c & 0xF`

2022-07-26 15:12 UTC, marmarek commented on qrexec-lib/unpack.c
> +            code_point = *untrusted_c & 0xF;
This in fact should be `*untrusted_c & 0x7`, but the result is the same as the 4-th bit is 0.

2022-07-26 15:12 UTC, marmarek commented on qrexec-lib/unpack.c
> +        case 0xED: case 0xEE: case 0xEF:
Once you made it a continuous range, you can represent it as one. But also, it now deviates from the comment above, which is exact syntax from the RFC. The comment should be more explicit how the code deviates from the RFC (pointing which range is "surrogates" and how are they encoded).

2022-07-26 15:12 UTC, marmarek commented on gentbl.py
> +        sys.exit(1)
Please stop. Regardless of the usual comment, you don't even use `assert` in this script at all.

2022-07-26 15:12 UTC, marmarek commented on gentbl.py
> +            if last_cat[0] in ('C', 'Z') and i != 0x21:
This `0x21` requires a comment, as it is fact about `0x20`.

2022-07-26 15:12 UTC, marmarek commented on qrexec-lib/unpack.c
> +        untrusted_nsec != UTIME_OMIT &&
Why allowing `UTIME_NOW` and `UTIME_OMIT`?

2022-07-26 15:12 UTC, marmarek commented on qrexec-lib/unpack.c
> +
Remove extra blank line.

2022-07-26 19:19 UTC, DemiMarie reviewed
Thanks for the suggestions @marmarek!

2022-07-26 19:19 UTC, DemiMarie commented on gentbl.py
> +        sys.exit(1)
Good point

2022-07-26 19:19 UTC, DemiMarie commented on gentbl.py
> +            if last_cat[0] in ('C', 'Z') and i != 0x21:
I decided to use a more obvious check instead, with a comment.

2022-07-26 19:19 UTC, DemiMarie commented on qrexec-lib/unpack.c
> +        untrusted_nsec != UTIME_OMIT &&
The old code allowed them, but I am fine with rejecting them.

2022-07-26 19:19 UTC, DemiMarie commented on qrexec-lib/unpack.c
> +        if (*path_dup) {
You actually cannot _call_ this function with an empty path.  An empty path will be rejected by `validate_path`, and if you do pass an empty path to this function, you will trip an assertion.

2022-07-26 19:19 UTC, DemiMarie commented on qrexec-lib/unpack.c
> +    static char *path_dup = NULL;
Fixed by making the caller responsible for memory management.

2022-12-27 23:43 UTC, marmarek commented
PipelineRetry

2022-12-28 05:54 UTC, marmarek commented
PipelineRefresh

2022-12-28 05:55 UTC, marmarek commented
This fails to build, forgot to commit a file?
```
DEBUG: unpack.c:257:10: fatal error: unpack-table.c: No such file or directory
DEBUG:   257 | #include "unpack-table.c"
DEBUG:       |          ^~~~~~~~~~~~~~~~
```

2022-12-28 16:14 UTC, DemiMarie commented
> This fails to build, forgot to commit a file?
> 
> ```
> DEBUG: unpack.c:257:10: fatal error: unpack-table.c: No such file or directory
> DEBUG:   257 | #include "unpack-table.c"
> DEBUG:       |          ^~~~~~~~~~~~~~~~
> ```

`unpack-table.c` is automatically generated, so I suspect a missing dependency in the makefile.

2022-12-28 22:52 UTC, marmarek commented
6475736 Remove redundant code in pathname handling
b21fa23 Drop a call to strlen()
2864cd2 Simplify loop
5fcfec0 Reject empty paths again

The last one is a bug fix to the first commit in this list - it wants to be squashed there.

2022-12-28 22:54 UTC, marmarek commented
As of a98f14f0f7d892b2107a28e51f13c7cccb2e777a it looks promising, but it requires some unit tests. And as discussed elsewhere, UTF-8 validation is worth putting into separate source file (or even library) to be reusable - it's too much code to duplicate (as did with initial UTF-8 parsing earlier).

2022-12-29 00:24 UTC, DemiMarie commented
> As of [a98f14f](https://github.com/QubesOS/qubes-linux-utils/commit/a98f14f0f7d892b2107a28e51f13c7cccb2e777a) it looks promising, but it requires some unit tests.

Do you want me to use escape sequences or literal UTF-8 characters

> And as discussed elsewhere, UTF-8 validation is worth putting into separate source file (or even library) to be reusable - it's too much code to duplicate (as did with initial UTF-8 parsing earlier).

Should there be an enum for the various types of validation?  File names, window titles, etc.

2022-12-29 00:37 UTC, marmarek commented
> Do you want me to use escape sequences or literal UTF-8 characters

Escape sequences are probably easier to handle from developer point of view (no dependency on rendering them properly in your editor, and no risk of exposing your editor to a bunch of weird unicode characters).

> Should there be an enum for the various types of validation? File names, window titles, etc.

There will be a need for various validation modes (just valid UTF-8, hopefully-safe to render, etc), so, yes, enum like that makes sense. But choose names carefully, to avoid situations where "window titles" mode is used for all kind of things, because it's a good mode for safe-to-render text.

BTW, I think `validate_utf8_char` will want ASCII handling restored, even if there is a fast path outside of it _in this particular case_.

2023-03-10 18:18 UTC, marmarek requested changes

2023-03-10 18:18 UTC, marmarek commented on qrexec-lib/Makefile
> +CFLAGS := $(CFLAGS) -I. -g3 -O2 -Wall -Wextra -Werror -pie -fPIC
What's the point of changing += ?

2023-03-10 18:18 UTC, marmarek commented on qrexec-lib/pure.h
> +/** A mutable slice.  Equivalent to Rust’s &mut [T]. */
```suggestion
/** A mutable slice.  Equivalent to Rust's &mut [T]. */
```

2023-03-10 18:30 UTC, DemiMarie commented on qrexec-lib/Makefile
> +CFLAGS := $(CFLAGS) -I. -g3 -O2 -Wall -Wextra -Werror -pie -fPIC
An earlier commit had `$(shell)` in the RHS.  `+=` caused the shell command to be run every time `CFLAGS` was used.

2023-03-10 19:22 UTC, DemiMarie commented
PipelineRetryFailed

2023-03-11 00:40 UTC, marmarek approved these changes

2023-03-11 01:36 UTC, merged